language: node_js
matrix:
  fast_finish: true
env:
  matrix:
  - COZY_APP_SLUG=drive
  - COZY_APP_SLUG=photos
  global:
  - REGISTRY_EDITOR=Cozy
  - secure: hmzHoeKZQDZtmlltZKZA+iT/nRShb0ggsmGYR5Ie5k2PuRQFr/aopI7TJZufg0wr457AXuS6xdcOYuhhwrlrX15dmB20tYCrz6IfIBvJohk1cKVRbkSC6VuExDrfFTZ7j/SAOXy9x6dIgDOj5Ktz5UW7ou934Fif+bbsSm28DMitCCZqqsP6szCTbmYpVjQZwwOZBPq8bqSe/wGZXKwkiSalPj0ueqEPAAN8gS6Y7fwjTRle/uU0JTPW6ehDU45d9B6GMspMph3hqzLWNV/D5z8oXINKyVVi6hQKfbWrZYScshdd4AvUdXBfDcg4rDeqxA9NG3J0EO5FD8/wO9cakz9uq/q04AsJiqHeCrrR4Sd3dIdxBAKZfV2LiVYqYppmQnkzWgKW1oZIh65Vy23+RxTRTAi9TfIP3H+dwS7LkeHKoYeGxxg9gUHC6S7Eb5VFCts4GQQUSkNhGoRTHx/l6Q2CuyBS8sgx+VfFMTGb4jqrOBk4t2TZWNcs/QKzVcXv/beybYZCwKLNW9EFnjMjP5GHIWYhXrE6g6Q024nSh2YeB5PbutioXNy8jMi9vF9dnI/qQ5gr0kH1MemMWTzJ3FzUA44T+cygN2rv4yWqU6BcuECv/+1G789151Ebib9LZK0Ja7ATJpltmZABeD2zRHi8pmhUQo4RZZy0LUyvun8=
script:
- sh publish_registry.sh
